### ISSUE TITLE
Got error when run command `emma`

### ISSUE THREAD

**Issue by taropoo** [maticzav/emma-cli#11]
Hi there,

Thank you so much for creating this tool, it looks awesome! However, after I install it, by running `npm install -g emma-cli`, everytime I enter `emma`, I get the following error:

```/usr/local/lib/node_modules/emma-cli/dist/emma.js:40
const canAccessFile = (0, _util.promisify)(_fs.default.access);
                                          ^

TypeError: (0 , _util.promisify) is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/emma-cli/dist/emma.js:40:43)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/emma-cli/dist/index.js:10:36)
    at Module._compile (module.js:570:32)```

**Comment by maticzav** [comment]
hey @taropoo 👋 I am so happy to hear that you like it. It seems like this is a node version problem, which node are you using?

**Comment by taropoo** [comment]
Ah you are right, I don't have the latest version. Let me update it and try again.

**Comment by taropoo** [comment]
Once I upgraded it's all good, thanks!

**Comment by maticzav** [comment]
No problem! Enjoy it! 😄
